### ISSUE TITLE
Send out list of best requests on each gold site (monthly?) with unique tracking links to partners, mailing lists

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#22]
## Q: Do stories in the media increase the growth of sites?

Send out list of best requests on each gold site (monthly?) with unique tracking links to partners, mailing lists

[Explain how you will measure this]

Track any traffic to the sites via these links

[What do we need to do to be able to take the measurements?]
- [ ] Get a list of good requests from gold sites
- [ ] Write in to email
- [ ] Find outlet for email

If we know requests and top social media sites we could do a quite targeted attempt to drive up traffic

**Comment by garethrees** [comment]
This is basically the same as https://github.com/mysociety/alaveteli-experiments/issues/18
